In [6]:
import numpy as np

In [7]:
def function1():
    n_arr=np.array([1,7,13,105])
    print(n_arr)
    print(f"NBYTES={n_arr.nbytes}")

In [8]:
function1()

[  1   7  13 105]
NBYTES=32


In [9]:
# 2.Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.


In [10]:
x = np.array([3, 5])
y = np.array([2, 5])

In [11]:
print("Comparison - greater")
print(np.greater(x,y))

print("Comparison - greater_equal")
print(np.greater_equal(x, y))

print("Comparison - less")
print(np.less(x, y))

print("Comparison - less_equal")
print(np.less_equal(x, y)) 

Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [12]:
#3. Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [13]:
arr1=np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
arr2=np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
arr3=np.ones(10)*5
print(arr3)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
arr4=np.ones(10)*10
print(arr4)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [17]:
arr5=np.ones(10)*20
print(arr5)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [18]:
arr6=np.ones(10)*50
print(arr6)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [19]:
#4.Write a NumPy program to create an array of integers from 30 to 70.


In [20]:
arr7=np.arange(30,71)
print(arr7)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [21]:
#5. Write a NumPy program to create an array of integers from 50 to 95.

In [22]:
arr7=np.arange(50,96)
print(arr7)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [23]:
#6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [24]:
arr8=np.arange(20,80,2)
print(arr8)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [25]:
#7. Write a NumPy program to create an array of all odd integers from 20 to 80.


In [26]:
arr8=np.arange(21,80,2)
print(arr8)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [27]:
#8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [28]:
arr9=np.random.randint(10,40,15)
print(arr9)

[36 11 33 38 23 30 35 21 10 24 12 29 22 36 32]


In [29]:
#9. Write a NumPy program to generate an array of 10 random numbers from 30 to 50.


In [30]:
arr9=np.random.randint(30,500,10)
print(arr9)

[ 55  37 296 333 154 178 302 283 192 234]


In [31]:
#10Write a NumPy program to generate an array of 20 random numbers from 50 to 90.


In [32]:
arr9=np.random.randint(50,90,20)
print(arr9)

[60 73 78 88 51 55 85 53 67 59 54 58 73 82 70 68 89 55 84 78]


In [33]:
#11. Create any two arrays & perform various mathematical operations.
   # i.e. Addition, Substraction, Multiplication, Divide.


In [36]:
n1=np.array([10,20,30])
n2=np.array([11,22,33])
print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 / n2)

[21 42 63]
[-1 -2 -3]
[110 440 990]
[0.90909091 0.90909091 0.90909091]


In [37]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.


In [38]:
m = np.arange(10, 22).reshape((3, 4))

In [39]:
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [43]:
#13.Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.


In [44]:
x = np.eye(3)

In [45]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
#14. Write a NumPy program to find the number of rows and columns in a given matrix.

In [47]:
m = np.arange(10, 22).reshape((3, 4))

In [49]:
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape) 

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


In [50]:
#.15 Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [53]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [55]:
#16.  Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.


In [56]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.07910105 0.27970211 0.13740325]
  [0.14891952 0.63905487 0.65740211]
  [0.53295639 0.2691124  0.55740756]]

 [[0.00675299 0.73111342 0.61006135]
  [0.24313587 0.7657185  0.12860787]
  [0.72135811 0.43486447 0.31770599]]

 [[0.28732163 0.5046272  0.58759303]
  [0.97253054 0.05639586 0.14216951]
  [0.61397422 0.04900344 0.90012746]]]


In [57]:
#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

In [59]:
x = np.random.random((2, 3, 4))
print(x)

[[[0.0981496  0.78117692 0.44942369 0.06152976]
  [0.53083221 0.1625717  0.95310922 0.16485275]
  [0.29126961 0.33430549 0.52035657 0.35383047]]

 [[0.35480226 0.62039392 0.01384213 0.44120741]
  [0.04199366 0.16237062 0.51055944 0.51903252]
  [0.64366483 0.76155413 0.32347832 0.15938445]]]


In [60]:
# 18.Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [61]:

l = [12, 13, 100, 36]

print("Original List:", l)
a = np.array(l)
print("One-dimensional NumPy array: ", a)

Original List: [12, 13, 100, 36]
One-dimensional NumPy array:  [ 12  13 100  36]


In [62]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.


In [63]:
x = np.arange(2, 11).reshape(3, 3)

print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [64]:
#20. Write a NumPy program to create an array with values ranging from 12 to 38.


In [65]:
x = np.arange(12, 39)
print(x)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [66]:
#21.Write a NumPy program to reverse an array (the first element becomes the last).


In [70]:
x = np.arange(12, 38)
print(x)

print("Reverse array:")
x = x[::-1]
print(x) 

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [71]:
#22. Write a NumPy program to convert an data type into to a floating type.


In [72]:

a = [1, 2, 3, 4]
print("Original array")
print(a)

x = np.asfarray(a)
print("Array converted to a float type:")
print(x) 

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [73]:
#23. Write a NumPy program to convert a list arra

In [76]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]  
  
arr = np.array(a)    
print ("List: ", a)   
print ("Array: ", arr)  

List:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Array:  [1 2 3 4 5 6 7 8 9]


In [77]:
#24 Write a NumPy program to get the element-wise remainder of an array of division.


In [78]:

x = np.arange(7)
print("Original array:")
print(x)

print("Element-wise remainder of division:")
print(np.remainder(x, 5)) 

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [79]:
#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [81]:
x = np.arange(20,51)
print("Original array:")
print(x)

print("Element-wise remainder of division:")
print(np.remainder(x, 3)) 

Original array:
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]
Element-wise remainder of division:
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
